In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
from sklearn.datasets import fetch_20newsgroups

In [17]:
train = fetch_20newsgroups(subset="train", random_state=42)
test = fetch_20newsgroups(subset="test", random_state=42)

In [18]:
train.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [20]:
test.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [21]:
cat = ['alt.atheism', 'sci.space', 'comp.graphics']

In [23]:
train = fetch_20newsgroups(categories=cat, random_state=42)

In [24]:
train.data

['From: degroff@netcom.com (21012d)\nSubject: Re: Venus Lander for Venus Conditions.\nOrganization: Netcom Online Communications Services (408-241-9760 login: guest)\nLines: 8\n\n\n  I doubt there are good prospects for  a self armoring system\nfor venus surface conditions (several hundred degrees, very high\npressure of CO2, possibly sulfuric and nitric acids or oxides\nbut it is a notion to consider for outer planets rs where you might\npick up ices under less extream upper atmosphere conditions buying\ndeeper penetration.  A nice creative idea, unlikly but worthy of\nthinking about.\n',
 'From: ab@nova.cc.purdue.edu (Allen B)\nSubject: Re: TIFF: philosophical significance of 42\nOrganization: Purdue University\nLines: 39\n\nIn article <prestonm.735400848@cs.man.ac.uk> prestonm@cs.man.ac.uk (Martin  \nPreston) writes:\n> Why not use the PD C library for reading/writing TIFF files? It took me a\n> good 20 minutes to start using them in your own app.\n\nI certainly do use it whenever I

In [26]:
train.target_names

['alt.atheism', 'comp.graphics', 'sci.space']

In [35]:
train.data[5]

'From: dietz@cs.rochester.edu (Paul Dietz)\nSubject: Commercial mining activities on the moon\nOrganization: University of Rochester\nLines: 38\n\nIn article <1993Apr20.152819.28186@ke4zv.uucp> gary@ke4zv.UUCP (Gary Coffman) writes:\n\n > be the site of major commercial activity. As far as we know it has no\n > materials we can\'t get cheaper right here on Earth or from asteroids\n > and comets, aside from the semi-mythic He3 that *might* be useful in low\n > grade fusion reactors.\n\nI don\'t know what a "low grade" fusion reactor is, but the major\nproblem with 3He (aside from the difficulty in making any fusion\nreactor work) is that its concentration in lunar regolith is just so\nsmall -- on the order of 5 ppb or so, on average (more in some\nfractions, but still very small).  Massive amounts of regolith would\nhave to be processed.\n\nThis thread reminds me of Wingo\'s claims some time ago about the moon\nas a source of titanium for use on earth.  As I recall, Wingo wasn\'t\nconte

In [38]:
train.target

array([2, 1, 0, ..., 2, 2, 2])

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
vector = CountVectorizer()
X = vector.fit_transform(train.data)
X = X.toarray()

In [42]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
Y = train.target

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [47]:
X_train.shape

(1159, 29663)

In [48]:
X_test.shape

(498, 29663)

In [49]:
y_train.shape

(1159,)

In [50]:
y_test.shape

(498,)

In [51]:
from sklearn.naive_bayes import BernoulliNB

In [52]:
model = BernoulliNB()
model.fit(X_train, y_train)

BernoulliNB()

In [54]:
y_pred = model.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [60]:
accuracy = accuracy_score(y_pred, y_test)
print(accuracy)

0.9056224899598394


In [61]:
cm = confusion_matrix(y_pred, y_test)
print(cm)

[[142   0   1]
 [ 16 167  29]
 [  0   1 142]]


In [62]:
report = classification_report(y_pred, y_test)
print(report)

              precision    recall  f1-score   support

           0       0.90      0.99      0.94       143
           1       0.99      0.79      0.88       212
           2       0.83      0.99      0.90       143

    accuracy                           0.91       498
   macro avg       0.91      0.92      0.91       498
weighted avg       0.92      0.91      0.90       498



In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [68]:
vector = TfidfVectorizer()
X = vector.fit_transform(train.data)
X = X.toarray()

In [69]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [70]:
Y = train.target

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [72]:
from sklearn.naive_bayes import MultinomialNB

In [73]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [74]:
y_pred = model.predict(X_test)

In [75]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [76]:
accuracy = accuracy_score(y_pred, y_test)
print(accuracy)

0.9859437751004017


In [77]:
cm = confusion_matrix(y_pred, y_test)
print(cm)

[[152   0   0]
 [  0 164   1]
 [  0   6 175]]


In [78]:
report = classification_report(y_pred, y_test)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       152
           1       0.96      0.99      0.98       165
           2       0.99      0.97      0.98       181

    accuracy                           0.99       498
   macro avg       0.99      0.99      0.99       498
weighted avg       0.99      0.99      0.99       498

